### ISSUE TITLE
Cached overlays are pale

### ISSUE THREAD

**Issue by lobsiger** [pytroll/pycoast#95] opened 2023-03-27 21:00 UTC
#### Problem description

Cached overlay outline and fill colors are pale. See this thread:

https://groups.google.com/g/pytroll/c/7VVgsmstLkQ

@djhoese  for unknown reason the google list deletes all my posts. I found out that the pycoast stored overlay.png
is already pale. I made a composite with a clean image of Switzerland and the stored overlay file using ImageMagick.
I get exactly the Satpy result for cached overlays. You can see with the bare eye that the cached overlay.png is pale.

![Switzerland-overlay](https://user-images.githubusercontent.com/101883219/228064724-e520c9c5-95bd-4148-ac2a-fa4f2197efcb.png)

**Comment by djhoese** [comment] 2023-03-27 21:03
@lobsiger It looks like google groups decided to require approval of your messages...but then also didn't notice any of the owners of the list that they need approval. Would you like me to approve one of the messages? If so, which time?

**Comment by lobsiger** [comment] 2023-03-27 21:17
@djhoese what do you mean with "which time"? Do I have to post a message to the google group at some known time? Or can you just approve my first post of this overlay problems thread?

**Comment by djhoese** [comment] 2023-03-27 22:02
Google groups shows multiple messages from you with different timestamps:

![image](https://user-images.githubusercontent.com/1828519/228076979-27054aad-2b74-4730-b912-6817ddff0297.png)

I assumed you tried to resend the message multiple times.

**Comment by lobsiger** [comment] 2023-03-28 08:51
@djhoese I logged in and could post and see my posts. But after logout the posts were deleted. I cleaned my gmail account, changed PW and approved my other e-mail account. Maybe this or some of your help gave me access to google group posts again. Regarding a fix for the pale cache file generation I will be of no help as this code is well over my head :-(. All I found out above is that the saved/cached overlay file is pale already. So the problem seems to be in the generation of this overlay file and not in the later application step.

**Comment by mraspaud** [comment] 2023-03-28 10:06
Hi @lobsiger,

This was a long time ago, but I was the one writing this code at this time.
From what I remember, the problem with the cache is that it can make no assumption on what color will be under it's coastlines, so it becomes lighter naturally. However, now that I think about it, maybe the way to apply the cached coastlines could be improved eg by multiplying instead of pasting the cache?
As you can see here https://github.com/pytroll/pycoast/blob/main/pycoast/cw_base.py#L1215
we use the paste function to put the cache lines on top of the background. Maybe there are better methods for this? for example the documentation of paste seems to hint at using something called `alpha_composite` instead, maybe that's better?
https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.paste

**Comment by lobsiger** [comment] 2023-03-28 11:44
... sorry, I should have taken the black MSLP chart. If you see all white above or even below (?) click on the invisible image :-).

![ukmos-bb-202303280600](https://user-images.githubusercontent.com/101883219/228225371-92274d52-ade9-4ca6-8405-4a4395386bd5.png)

**Comment by mraspaud** [comment] 2023-03-28 12:21
The thing is that when using antialiased lines as drawn with the AGG backend, some pixels of the lines are somewhat transparent, hence the need to take care of alpha blending.

**Comment by lobsiger** [comment] 2023-03-28 13:23
@mraspaud O.K. I grasp that writing a fine antialiased line on some background might not be the same thing as writing this line on a transparent canvas (I eliminate antialiasing in my MSLP charts). But what about the fill colors? When these are fully opaque I see no difference. But when I fill e.g. land masses with 'fill': (255,0,0) of 'fill_opacity': 127 I do not understand the difference seen between cached and non cached results below (red in cached image is much more dim).


![MetopB-20230327-DAY-0923-natural_color-eurol10-cacheFalse](https://user-images.githubusercontent.com/101883219/228250206-9a634255-4d5c-4ad3-89a5-cf3cee663afa.jpg)
![MetopB-20230327-DAY-0923-natural_color-eurol10-cacheTrue](https://user-images.githubusercontent.com/101883219/228250211-fdd55ef9-fb61-44ad-a0c2-2cd555cd7dc8.jpg)

**Comment by lobsiger** [comment] 2023-03-28 16:23
@mraspaud @djhoese  maybe this is one more hint: If I generate the above image without cache but 'fill' : (127, 0, 0) and 'fill_opacity': 127 I get (apparently) exactly the same red fill colors as with cached 'fill': (255, 0 ,0) and 'fill_opacity': 127. 
Is in the cached case the red (255, 0, 0) fill color arithmetically blended with black (0, 0, 0) somehow?

**Comment by djhoese** [comment] 2023-03-28 16:32
Hhhmmm just a thought, but when the cache image is first created the base Image is created as all black with full transparency (`RGBA=(0, 0, 0, 0)`). I wonder if we did it `(255, 255, 255, 0)` if that would make a difference?

**Comment by djhoese** [comment] 2023-03-28 16:33
Here is where the change would go:

https://github.com/pytroll/pycoast/blob/4687a0ea4fa4b3bf630baec907b92cd06a01c5ff/pycoast/cw_base.py#L1178

**Comment by lobsiger** [comment] 2023-03-28 17:02
@djhoese I could try that but I do not expect it to work. If my idea of blending above has some truth then the problem is rather how the lines and fill values are written onto this black surface. The involved (0,0,0,0) pixels should be replaced. For pixels not touched (0,0,0,0) would remain as "no_data" value. Fine lines might suffer the antialiasing problem @mraspaud mentioned.

**Comment by djhoese** [comment] 2023-03-28 17:14
I won't promise/guarantee that this will fix things, but I've seen something like this in the VisPy library that I maintain. When two colors are blended, especially when transparency is involved, the mix between black (0) and any color is a reduced version of that color, the mix between whitee (255) and any color should at least be the original color. ...this is my hope at least.

**Comment by lobsiger** [comment] 2023-03-28 18:48
As a last variant I tested 'fill':(255,0,0) and 'fill_opacity': 127 with overlay cache True starting with a red RBGA = (255, 0, 0, 0) canvas for the overlay file. This basically gives me the original image with no cache ( (red+red)/2=red ??) while the thin minor grid lines now get some red from the @mraspaud mentioned antialiasing. I still think the problem has to do how the colors are applied on the empty base image. No idea whether and where this can be changed/improved.

![MetopB-20230327-DAY-0923-natural_color-eurol10-cacheTrue-red-base-image](https://user-images.githubusercontent.com/101883219/228337575-7911ab3d-d715-4bea-ac43-0dd0274406c1.jpg)

**Comment by lobsiger** [comment] 2023-03-28 19:19
@djhoese  I'm not sure this is of any help. I make these images with my module LEOstuff.py
that does about everything for LEO sats. I only copied the most relevant overlay parts used.


# Area used

eurol10:
  description: Euro 10.0km area - Europe
  projection:
    proj: stere
    ellps: WGS84
    lat_0: 90.0
    lon_0: 0.0
    lat_ts: 60.0
  shape:
    height: 800
    width: 1000
  area_extent:
    lower_left_xy: [-3780000.0, -7644000.0]
    upper_right_xy: [3900000.0, -1500000.0]

    #############################################################################
    # sf is a scale factor depending on image size sf = (width + height) / 3000 #
    #############################################################################

    sf = (1000 + 800) / 3000

    my_coasts  = {'outline': (255, 255,   0), 'outline_opacity': 255, 'width': 1.5*sf, 'level': 1, 'fill': (255, 0, 0), 'fill_opacity': 127}
    my_borders = {'outline': (255,   0,   0), 'outline_opacity': 255, 'width': 1.0*sf, 'level': 1}
    my_rivers  = {'outline': (  0,   0, 255), 'outline_opacity': 255, 'width': 1.0*sf, 'level': 3}

    my_grid  = {'major_lonlat': (10,10), 'minor_lonlat': (2, 2),
                # Opacity 0 will hide the line, values 0 ... 255  EL
                'outline': (255, 255, 255) , 'outline_opacity': 255,
                'minor_outline': (200, 200, 200),'minor_outline_opacity': 127,
                'width': 1.5*sf, 'minor_width': 1.0*sf, 'minor_is_tick': False,
                'write_text': True, 'lat_placement': 'lr', 'lon_placement': 'b',
                'font': fontdir + '/DejaVuSerif.ttf',
                'fill': 'white', 'fill_opacity': 255, 'font_size': 30*sf}
                # minor_is_tick: False draws a line not ticks, True does ticks
                # label placement l,r,lr for latitude and t,b,tb for longitude

**Comment by djhoese** [comment] 2023-03-29 17:51
I'm playing around with this in #96 (mostly doc fixes at the moment). But while I was working on making a failing unit test I discovered that if you don't use a background image (so always return the overlays with a transparent background) that the results are always equal. So the cached result, the image generated from reusing the cached image (expected), and generating the image without the cache. This is obvious when you think about it since we never combine the foreground with a background, but I just wanted to point it out.

**Comment by djhoese** [comment] 2023-03-29 18:07
@lobsiger @mraspaud I've noticed an inconsistency with `add_overlays_from_dict`. The docstring suggests it should always return a transparent image with the overlays added on to it. However, I've noticed that this is only true if caching is enabled. If you disable caching and provide a background image then it returns the background image with the foreground overlays applied. I think this has to do with the way the code is written and how it treats foreground/background.

Is this OK with us? I think the inconsistency between cache and no cache in this sense makes it undesirable.

**Comment by djhoese** [comment] 2023-03-29 18:11
hhhmm but maybe that's a performance issue since in the non-cached case you'd be generating a whole new image in memory and then applying it. :thinking:

**Comment by lobsiger** [comment] 2023-03-29 18:47
@djhoese @mraspaud yes of course caching is before all a performance thing especially if you generate many composites of the same scene that are resampled with generate=False (as I do). TBH my English and/or brain is not good enough to understand what you stated 3 post above. Is there a way to cache an overlay without using an image file on a disk? I came to the conclusion that as long as we (must?) use the PIL Image.paste()

https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.paste

there is no way to make final results using cached image files equal to writing all overlays directly on top of the generated satellite image. If I understand it right the Image.paste() uses the A channel as mask. Only if a pixel has A=255 it is not combined with the background. That means the big differences will always be with fine lines (due to antialiasing) and in surfaces filled with some transparency (the lakes I added). That's how I finally noted the difference that must have been there for many years.

**Comment by djhoese** [comment] 2023-03-29 19:07
@lobsiger I think the antialiasing is going to be an issue for lines of any size, but yes they are maybe more noticeable for fine lines since the percentage of the line that is semi-transparent is much higher.

Some questions for you:

The images you are pasting here in this issue, are they the exact image saved by your code or are they screenshots of what you are seeing? Either way, in your image viewer do you set a background color for images? I have my image viewer set to show a checkerboard pattern underneath an image so when an image is transparent I can see a checkerboard. Here is what I'm seeing with the text I'm making where the square in the upper-right has an opacity of 127.

The final image using caching:

![image](https://user-images.githubusercontent.com/1828519/228641656-500f4f90-5976-45a1-b8ca-ed43dc444047.png)

The final image without caching:

![image](https://user-images.githubusercontent.com/1828519/228641800-7a367347-048f-4a24-8293-251474d08bd9.png)

So it seems the blending done by `.paste` during caching is overwriting the alpha channel instead of adding (taking the maximum is maybe appropriate?) to it. I would expect for a black background with alpha=255 and an overlay shape of alpha=127 that the final result has an overall alpha of 255 but the green color of the square is mixed between black (0, 0, 0) and pure green (0, 255, 0).

Can someone sanity check me on this? I'll look into using some of the other masking and alpha_composite options and see how it changes things.

**Comment by lobsiger** [comment] 2023-03-29 19:25
@djhoese the images sort from satpy as *.png. Then in a last step I add the legend at left with Image Magick (IM) and change to *.jpg. I do not see a difference of the satpy issued *.png and the *.jpg. Normally I finally make *.webm images because these compress much better than *.jpg. But github does not accept *.webm files added to comments. Except for IM nothing else is used.

**Comment by djhoese** [comment] 2023-03-29 19:36
Ah JPEG doesn't support transparency anyway. I'm not sure why you wouldn't be seeing a difference between .png and .jpg unless your image viewer is using a black background behind the image. Anyway, I'll keep playing with this. I've got the caching output to be decently consistent and what I expect by using `alpha_composite`, but without caching it is still doing something funny (not using transparency on the green square so it shows full brightness).

**Comment by lobsiger** [comment] 2023-03-29 19:41
I think the PIL docs of Image.paste() explain what we see:
"
If a mask is given, this method updates only the regions indicated by the mask. ...... Where the mask is 255, the given image is copied as is. Where the mask is 0, the current value is preserved. Intermediate values will mix the two images together, including their alpha channels if they have them."

As a mask we use the overlay (foreground) A channel. As long as I use colors with opacity 255 (like in the Cities and Points symbols and their labels added) there is no difference. In thin lines even the center pixels might have opacity < 255 and are mixed with the black background "including alpha". That's why borders and rivers are always dim red and dim blue when cached.

**Comment by lobsiger** [comment] 2023-03-29 20:00
I know that *.jpg has no transparency. Maybe my FireFox browser hides some differences that you see in special image processors. The only problem with transparencies I remember was Himawari *.png images way outside the full disk. I always use nodata_values either black or white. If you think it helps somehow I can further shrink the eurol10 area used so far and post the output *.png without the IM step. As seen above with my all white "Bracknell" MSLP chart it changes when you click on it.

**Comment by djhoese** [comment] 2023-03-30 02:09
Here's a very simple test I'm doing:

```python
        from pycoast import ContourWriterAGG

        proj4_string = "+proj=longlat +ellps=WGS84"
        area_extent = (-10.0, -10.0, 10.0, 10.0)
        area_def = FakeAreaDef(proj4_string, area_extent, 200, 200)
        cw = ContourWriterAGG(gshhs_root_dir)

        test_shape_filename2 = tmp_path / "test_shapes2"
        with shapefile.Writer(test_shape_filename2) as test_shapes:
            test_shapes.field('name', 'C')
            test_shapes.poly([[[5.0, 10.0], [10.0, 10.0], [10.0, 5.0], [5.0, 5.0]]])
            test_shapes.record("upper-right-box")

        overlays = {
            "cache": {"file": os.path.join(tmp_path, "pycoast_cache")},
            "shapefiles": [
                {"filename": str(test_shape_filename2), "fill": (0, 255, 0), "outline": (255, 255, 0), "fill_opacity": 127},
            ],
        }

        # Create the original cache file
        print("Before initial cache")
        background_img1 = Image.new("RGBA", (200, 200), (0, 0, 0, 255))
        cached_image1 = cw.add_overlay_from_dict(overlays, area_def, background=background_img1)

        # Reuse the generated cache file
        print("Before cache reuse")
        background_img2 = Image.new("RGBA", (200, 200), (0, 0, 0, 255))
        cached_image2 = cw.add_overlay_from_dict(overlays, area_def, background=background_img2)

        # Create without cache
        overlays.pop("cache")
        print("Before no cache")
        background_img3 = Image.new("RGBA", (200, 200), (0, 0, 0, 255))
        nocache_image = cw.add_overlay_from_dict(overlays, area_def, background=background_img3)

        # Manually (no dict, no cache)
        background_img4 = Image.new("RGBA", (200, 200), (0, 0, 0, 255))
        cw.add_shapefile_shapes(background_img4, area_def, **overlays["shapefiles"][0])
```

So with changing things in the caching logic to use `alpha_composite` I get what I expect from these operations in the `background_imgX` objects. That is, I get a black background and a green square in the upper-right but the green square is "faded" like it has an opacity of 127 applied to it *but* the square is not transparent like the checkerboard images I showed above.

*Now* the problem is that in last two cases of the above code (no cache and "manual") the green square is completely bright like the opacity isn't having any effect. I'll have to continue debugging tomorrow.

**Comment by djhoese** [comment] 2023-03-30 02:17
Nevermind, I did another shape that is fully opaque green and it is clear that the partially transparent one is paler in the cached image, less pale in the manual image, and both are not as bright as the fully opaque one. So...I might just be in the same position as I was when I started today.

**Comment by djhoese** [comment] 2023-03-30 02:20
I wonder if this is a pre-multiplied alpha versus regular alpha kind of thing. Where the colors in the saved/cached image are already multiplied by alpha so when we do the `alpha_composite` is doesn't work right.

**Comment by lobsiger** [comment] 2023-03-30 13:48
@djhoese as you suggested https://github.com/pytroll/pycoast/issues/95#issuecomment-1489190995 I add two (size reduced) *.png exactly as those are written by satpy. I see no difference with the *.jpg versions in the FireFox browser and in the Windows supplied image processing programs they also look the same (I see no remaining transparency or checkerboard). So it seems this adds nothing new.

With the knowledge *I think* to have now I'd rather close this issue. I see no solution for resolving the antialiasing issue. Writing an antialiased white line on a bunch of different composite images cannot be replaced by a cached line that does not yet know on what background it will be applied later. If not already there (and overlooked by me) a note in RTD might be appropriate.

![MetopB-natural_color-eurol15-cacheFalse](https://user-images.githubusercontent.com/101883219/228856227-03d9d4c7-17b2-4c0a-92f9-9137f5b56464.png)
![MetopB-natural_color-eurol15-cacheTrue](https://user-images.githubusercontent.com/101883219/228856298-1abc1e8e-7485-4faf-9187-c32b918f91af.png)

**Comment by djhoese** [comment] 2023-03-30 13:54
Interesting...but I think I've actually figured this out. I just need to implement it and test it. I'll push it to my PR and then you can let me know what you think. This is essentially a pre-multiplied alpha issue from what I can tell. The cache image being on a black background is causing any semi-transparent pixels to get multiplied by the alpha value (in combination with the black background) which reduces the color of the provided value. For example, drawing with a fill color of `(0, 255, 0, 127)` is resulting in the cached image being `(0, 126, 0, 126)`. When it is then applied to the background image (which is (0, 0, 0, 255) in my tests) the final result is `(0, 62, 0, 255)`. If you "reverse" the alpha multiplication you get a value near what you expect:

```
In [4]: 62 * (255 / 126)
Out[4]: 125.47619047619047
```

I'm sure there is some floating point issues going on here, but this is a pretty good sign from what I can see.

**Comment by djhoese** [comment] 2023-03-30 18:13
I added more tests and things seem to be as I expect. If you could test that branch of mine that'd be great. You should be able to do:

```
pip install git+https://github.com/djhoese/pycoast.git@bugfix-dull-cache
```

**Comment by lobsiger** [comment] 2023-03-30 18:33
@djhoese I replaced half an hour ago by hand 2 existing lines with: 

...
    fg = foreground.convert("RGBa")
    background.paste(fg, mask=fg)
...
            premult_foreground = self._foreground.convert("RGBa")
            self._background.paste(premult_foreground, mask=premult_foreground)
...
And I get the same results as before. Did I miss something? Does your pip install line change much more?

**Comment by lobsiger** [comment] 2023-03-30 18:35
Maybe it's a cache thing of the Firefox browser. I close and login again.

**Comment by djhoese** [comment] 2023-03-30 18:38
Hm, those are definitely the most important lines. I don't think any of the other changes would have an effect. :thinking: :confused:

**Comment by lobsiger** [comment] 2023-03-30 18:50
@djhoese I tried once more. Deleted the cached overlay file, closed and reopened the browser. Results are exactly (visually) as before https://github.com/pytroll/pycoast/issues/95#issuecomment-1486881288  Do your tests show something else?

**Comment by djhoese** [comment] 2023-03-30 18:54
My unit tests show differences, but I just tried a real world case and you are correct, things don't look correct. I will triple check, but it looks like was I posted before. That is, the overlay polygons (filled coastlines, etc) retain their alpha value from the overlay so you get a transparent polygons showing the "background":

![image](https://user-images.githubusercontent.com/1828519/228935856-466d4a37-68a3-428a-b9eb-f5551c1a607c.png)

So in my image viewer the background is a checkerboard. It makes sense for the space pixels in the upper-left (invalid pixels), but the green portions are supposed to be combined with the opaque layer below. Although...I'm actually even more confused by the fact that I'm specifying a fill color for "coastlines" and it is being used for all of those countries in the Caribbean.

**Comment by djhoese** [comment] 2023-03-30 18:58
Ok when I actually install the right version of pycoast (my PR) I get:

![image](https://user-images.githubusercontent.com/1828519/228936935-389ff578-18c9-47c7-96df-5593d38a12b5.png)

If you look closely at the green regions (not sure they show up in the tiny screenshot) you can see the clouds underneath the green.

**Comment by lobsiger** [comment] 2023-03-30 19:04
@djhoese my pillow is 9.2.0. Do you think your test (with the PR) above is now what you expect?

**Comment by djhoese** [comment] 2023-03-30 19:09
@lobsiger Triple check that you don't have any of the other changes that we played with before I finished my PR (like the all-white cache starting color or playing with alpha_composite if you did that).

**Comment by lobsiger** [comment] 2023-03-30 19:18
@djhoese I made a backup copy when we started *.sik. Here is the diff:

(pytroll) eumetcast@kallisto:~/miniconda3/envs/pytroll/lib/python3.10/site-packages/pycoast$ diff cw_base.py.sik cw_base.py
1202c1202,1204
<                     background.paste(foreground, mask=foreground.split()[-1])
---
>                     # background.paste(foreground, mask=foreground.split()[-1]) DEBUG
>                     fg = foreground.convert("RGBa")
>                     background.paste(fg, mask=fg)
1215c1217,1219
<             self._background.paste(self._foreground, mask=self._foreground.split()[-1])
---
>             # self._background.paste(self._foreground, mask=self._foreground.split()[-1]) DEBUG
>             premult_foreground = self._foreground.convert("RGBa")
>             self._background.paste(premult_foreground, mask=premult_foreground)
(pytroll) eumetcast@kallisto:~/miniconda3/envs/pytroll/lib/python3.10/site-packages/pycoast$

**Comment by djhoese** [comment] 2023-03-30 19:22
:confused: I...I...I don't know what else could be going wrong. If you are sure you are using that pytroll environment when you run your stuff then this should just work. It doesn't even matter if you have old cached images because all of these fixes should happen after loading the cached image, not during its creation.

What version of aggdraw? Are you using the `ContourWriterAGG`?

**Comment by lobsiger** [comment] 2023-03-30 19:28
AFAIK only agg has opacity.
aggdraw                   1.3.16          py310hb761d4a_0    conda-forge
Maybe it's not a good idea to edit files in a conda environment (but all other changes worked somehow)?

**Comment by lobsiger** [comment] 2023-03-30 19:38
Sorry, I have no development environment here. This is just a plain Satpy install. So I'm afraid no tests available. I'm running from some sub directory I have  all the scripts I'm testing ... I'm a little bit reluctant to pip install into a conda install. Do you think that will work?

**Comment by djhoese** [comment] 2023-03-30 19:42
> This is just a plain Satpy install. So I'm afraid no tests available.

I'm not sure what you mean. You mean you don't have `pytest` installed? Otherwise, the changes made in my PR should make sure all test data is now included in the sdist and wheel packages when they are installed. This should mean anyone installing pycoast can run the entire test suite.

>  I'm a little bit reluctant to pip install into a conda install. Do you think that will work?

It is what I'm doing, but I understand the hesitation. It does mean you have to be careful later on though if you then wanted to install the conda version of the package. One thing you could do is:

```
pip install --no-deps git+https://github.com/djhoese/pycoast.git@bugfix-dull-cache

# do your checks

pip uninstall -y pycoast
```

If you then do `conda list pycoast` it should be clear whether or not it has it installed. You can always do `conda install --force-reinstall pycoast` to make sure you get the conda version fully reinstalled.

Note the `--no-deps` above which should ensure that pip doesn't install a pip/PyPI version of a package that is already installed via conda (besides pycoast of course).

**Comment by lobsiger** [comment] 2023-03-30 19:53
O.K. installed with pip. Checked I got your PR file. Tried with generate=True and generate=False. Results are as before.

**Comment by djhoese** [comment] 2023-03-30 19:54
Can you try running `pytest --pyargs pycoast.tests`? You'll have to have pytest installed, but otherwise I think all the dependencies for running the tests should already be installed.

**Comment by lobsiger** [comment] 2023-03-30 20:06
@djhoese I get errors. Do I have to run the tests from inside the pycoast directory?

**Comment by djhoese** [comment] 2023-03-30 20:15
Ok so I'm currently fixing some things. The tests don't work properly if run from outside a source directory.

Your specific error above is that you're missing the `pytest_lazyfixture` package:

```
pip install pytest-lazy-fixture
```

Sorry about that. I forgot that one.

**Comment by lobsiger** [comment] 2023-03-30 20:21
I get a hell of failed tests. Do I have to start inside the test directory?

**Comment by djhoese** [comment] 2023-03-30 20:22
Wait until I fix the issues I've discovered related to running tests from an installed package.

**Comment by djhoese** [comment] 2023-03-30 20:36
Ok I just pushed a commit. Try reinstalling from the PR and running the tests. You should expect ~6 failing tests due to conda-forge only having Pillow 9.2.0, but the tests being written for Pillow 9.4.0 where some index rounding causes text labels to be shifted by one pixel.

**Comment by lobsiger** [comment] 2023-03-30 20:41
Yes 6 tests failed: 
=============================================== short test summary info ================================================
FAILED miniconda3/envs/pytroll/lib/python3.10/site-packages/pycoast/tests/test_pycoast.py::TestContourWriterPIL::test_grid[grid_germ.png-shape3-area_def3-4-grid_kwargs3] - AssertionError: Writing of grid failed
FAILED miniconda3/envs/pytroll/lib/python3.10/site-packages/pycoast/tests/test_pycoast.py::TestContourWriterPIL::test_add_grid_from_dict_pil - AssertionError: Writing grid from dict pil failed
FAILED miniconda3/envs/pytroll/lib/python3.10/site-packages/pycoast/tests/test_pycoast.py::test_shapes[cw_pil-western_shapes_pil.png-area_def0-specific_kwargs0] - AssertionError: Writing of shapes failed
FAILED miniconda3/envs/pytroll/lib/python3.10/site-packages/pycoast/tests/test_pycoast.py::test_shapes[cw_pil-eastern_shapes_pil.png-area_def1-specific_kwargs1] - AssertionError: Writing of shapes failed
FAILED miniconda3/envs/pytroll/lib/python3.10/site-packages/pycoast/tests/test_pycoast.py::test_no_scratch[cw_pil-no_h_scratch_pil.png-shape0-area_def0-specific_kwargs0] - AssertionError: Writing of no_scratch failed
FAILED miniconda3/envs/pytroll/lib/python3.10/site-packages/pycoast/tests/test_pycoast.py::test_no_scratch[cw_pil-no_v_scratch_pil.png-shape1-area_def1-specific_kwargs1] - AssertionError: Writing of no_scratch failed
================================ 6 failed, 57 passed, 187 warnings in 69.52s (0:01:09) =================================

**Comment by djhoese** [comment] 2023-03-30 20:45
Ok so none of those tests are the cache ones which show/test the things I changed in the PR. So if you run your scripts for generating your images and you're still seeing no change then something else is going on. Or I haven't fixed one of the issues you're running into. You're saying you're not seeing a difference in the PNGs generated by Satpy? How are you running your script? Is there any chance it isn't using the environment you think it is (a hashbang at the top of the file and you're running it like `./my_script.py`)?

And by no change, you're saying there is still clearly a difference between the no cache and cached final results?

**Comment by lobsiger** [comment] 2023-03-30 21:13
I start the script with python Sat-area.py yyyymmddDAY and it gives me a day pass of satellite Sat over area at dateDAY (NIG).
The script uses my module LEOstuff.py in the same directory. I have no other pytroll environment but the one I use on this machine. I just tried with Sentinel-3X over Switzerland today. It looks exactly the way we started. Should I try on another PC?

![Sen3X-20230330-DAY-1013-hugo211709n-switzerland-multi-blend_with_weights-cacheFalse](https://user-images.githubusercontent.com/101883219/228965286-eb1ffca9-cc3b-463d-888d-7a6ac69b9a19.jpg)
![Sen3X-20230330-DAY-1013-hugo211709n-switzerland-multi-blend_with_weights-cacheTrue](https://user-images.githubusercontent.com/101883219/228965290-f432e6c3-898c-48bb-b7ac-147eae225d79.jpg)

**Comment by djhoese** [comment] 2023-03-30 22:02
Yeah, thanks for sticking with this so late. Normally I would suggest doing `pip uninstall -y pycoast` then `conda uninstall --foce pycoast` then do the `pip install` of my PR again just to be sure, but you ran the tests. The tests that matter passed. The only differences between your above two images are cache on and off?

**Comment by lobsiger** [comment] 2023-03-31 11:49
O.K. I have now one install on another PC where it seems to work. I make a complete new install of miniconda and satpy on the PC from yesterday. Stay tuned ...

**Comment by lobsiger** [comment] 2023-03-31 19:40
@djhoese forget what I said about save_dataset() versus save_datasets(). In fact my complicated scripts also use save_dataset() in a for loop when lists of composites are  done with generate=True. With generate=False (only possible in the complicated scripts) save_objects.append() is used and finally compute_writer_results(save_objects). But neither generate=True nor generate=False works while for the simple scripts generate=True is AFAIK the default because nothing is specified.

I'll now try to slim down working (PR seems good) and non working (PR has no effect) variants of the scripts to a bare minimum.

**Comment by lobsiger** [comment] 2023-04-01 15:33
@djhoese @mraspaud after hours of desperation it seems I figured it out. In my sophisticated scripts I save the *.png images using a fill_value e.g. **scn.save_dataset(composite, filename, overlay={...}, fill_value=0/255)**. These fill_values (black/white) are needed for the case of MSLP overlays applied on GEO images by IM. I have white on transparent and black on transparent overlays as shown here https://github.com/pytroll/pycoast/issues/95#issuecomment-1486702515 and here https://github.com/pytroll/pycoast/issues/95#issuecomment-1486715226 . The point is now that in my older scripts I used no fill_value at all. In fact these fill_values make the #96  fail when using cached pycoast overlays while they have no effect on dim cached overlays in pycoast 1.6.1.

I must slightly adjust the logic in my latest scripts. I rarely use MSLP overlays combined with cached pycoast overlays. So instead of default **black** I could define these fill values default **None**. I'm not yet sure what this means for Himawari full disk images though.

**Comment by djhoese** [comment] 2023-04-01 15:47
> MSLP

What does this acronym stand for?

> IM

What does this acronym stand for?

When you use `fill_value=0` the image should be saved/enhanced/finalized as an RGB. Are you therefore saying that my PR doesn't work with plain RGB images (compared to RGBA images which are generated with the default `fill_value=None`)?

**Comment by lobsiger** [comment] 2023-04-01 17:00
@djhoese 

MSLP = Mean Sea Level Pressure (see my referenced images)
IM = Image Magick (best command line image processor)

Below are 3 NOAA20 VIIRS images of Switzerland showing a grid with opacity=127.  I made these images with cache enabled and your #96. The pictures were saved as *.png with fill_value=0, fill_value=255 and fill_value=None. Only with fill_value=None I get the same image as when I make the without pycoast overlay cache (where the fill_value seems not to matter for Switzerland at all).


![NOAA20-natural_color-switzerland-cacheTrue-fill_value0](https://user-images.githubusercontent.com/101883219/229304274-f747b3f7-dfdc-4ffc-9242-36ff380c83aa.png)
![NOAA20-natural_color-switzerland-cacheTrue-fill_value255](https://user-images.githubusercontent.com/101883219/229304285-1223d57e-e791-48fc-920e-455617f31a29.png)
![NOAA20-natural_color-switzerland-cacheTrue-fill_valueNone](https://user-images.githubusercontent.com/101883219/229304296-379ed26b-39e1-4a97-bd9d-346671e7a79f.png)

**Comment by lobsiger** [comment] 2023-04-01 17:33
_**When you use fill_value=0 the image should be saved/enhanced/finalized as an RGB. Are you therefore saying that my PR doesn't work with plain RGB images (compared to RGBA images which are generated with the default fill_value=None)?**_

Yes, that's probably what I say. Without cache enabled I get 24Bit (RGB) and 32Bit (RGBA) images that look all the same.
With your PR and cache enabled the 24Bit (RGB) look dim, only the 32Bit (RGBA) with fill_value=None looks as expected.

**Comment by djhoese** [comment] 2023-04-01 17:33
Ok, I'll try to take a look at this as soon as I can. I should be able to easily add this to my tests and make it work.

At the same time as waiting for your tests, I started working on fixing support for lon/lat projections that don't have a prime meridian at 0 longitude. You can do this in PROJ.4 with `+pm=180` for example and I use this for data that crosses the antimeridian. At the same time as all of this I think I've also discovered an additional check at excluding certain polygons from being added that would cause lines across the image. And...I may have a faster way to do this than we do currently (in numpy versus for loops).

**Comment by lobsiger** [comment] 2023-04-01 20:02
AFAIK imaging data that crosses the date line is not a problem. In cylindrical projections you can always specify lon_0. One thing to keep in mind is that the GSHHG  shapes we are using never cross the date line (there is one sea boundary exception, a BUG I guess). Below today's MSLP overlays of the Pacific.  You can also see why I need fill_value=0 here before IM can make the final overlay.



![GOES18-20230401-SLO-1200-airmass-opcpe-wc](https://user-images.githubusercontent.com/101883219/229311455-2c479660-261a-4521-9bb4-1e6cb65fc9fa.jpg)
![HIMA9-20230401-SLO-1200-airmass-opcpw-wc](https://user-images.githubusercontent.com/101883219/229311456-ae3113a4-41f0-4ac9-b1ff-22085832a191.jpg)

**Comment by djhoese** [comment] 2023-04-01 20:24
I've experienced problems with non-prime meridian projections. That's why I'm fixing it. For example, the Euro-Asia in the coastline "i" resolution is in view of an image in the pacific ocean but also crosses the regular prime meridian (the antimeridian of my projection).

As for your need for fill value. Could you explain it in more detail? Either way I need to fix RGB handling, but I'm not sure what I should be noticing in your images.

**Comment by lobsiger** [comment] 2023-04-01 21:15
Yes Euro-Asia is a problem that we have discussed years back. Can you specify the area in yaml style that makes the problems?

My MSLP overlays are mostly transparent RGBA *.png downloaded from NOAA, DWD and UK MetOffice  and heavily preprocessed with IM. If I use white MSLP contours and the area leaves the GEO satellite's data coverage like in the to right corner of the **opcpw** Himawari image above, I need a black background to see the MSLP contours applied by IM. If my MSLP charts are preprocessed as mainly black as here https://github.com/pytroll/pycoast/issues/95#issuecomment-1486715226 I need a white background for MSG3 (now moved to 0°) images that have no data top left.

**Comment by djhoese** [comment] 2023-04-02 19:48
So the area is something like this:

```
my_area:
  description: my_area
  projection:
    proj: longlat
    ellps: WGS84
    pm: 180
    no_defs: null
    type: crs
  shape:
    height: 9359
    width: 7818
  area_extent:
    lower_left_xy: [-2.7155727783203125, -5.613152448272707]
    upper_right_xy: [41.84626430664063, 47.73362392578125]
```

As for RGB handling, yep I definitely see the errors when I add it to my tests.

**Comment by djhoese** [comment] 2023-04-02 20:45
@lobsiger I just updated my PR with fixes for RGB. Let me know if it works for you.

**Comment by djhoese** [comment] 2023-04-03 17:10
I'm not sure if you noticed this in your own testing, but in the unit tests I had to allow for a difference between cached and non-cached versions of the overlays of 1 (in the unsigned 8-bit space). It seemed to me that floating point errors were causing the small difference (mainly how the pre-multiplied alpha is used).

With the above floating point differences and PNG internal compression, maybe that's enough to justify the differences you're seeing in file size. :man_shrugging: 

Thanks for all the testing. I'll give the other pycoast maintainers a chance to review the PR and then merge it.

**Closed** 2023-04-03 21:24 UTC
Labels: bug
